{% set name = "pysages" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SSAGESLabs/PySAGES/archive/v{{ version }}.tar.gz
  sha256: d1c6fe841abee5c618e6046746011628d9986748cad822faa1479796f7da8923

build:
  noarch: python
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=41.0
    - wheel >=0.33
    - numpy >=1.16
    - cython >=0.29
    - setuptools-scm >=6.0
    - pip
  run:
    - python >=3.6
    - cython
    - jax
    - numba
    - plum-dispatch

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/SSAGESLabs/PySAGES
  summary: Python Suite for Advanced General Ensemble Simulations
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jan-janssen
